export const LOGIN_MESSAGES = [
  'Hi! Before we start, could you log in, please?',
  'Please log in to proceed with your request.',
  'Welcome! Kindly log in to continue.',
  'To assist you better, please log in.',
  'Log in to access personalized assistance.',
  'Hello! Please log in to get started.',
  "Before proceeding, ensure you're logged in.",
  "Your next step is to log in. Let's begin!",
  'Access your account by logging in first.',
  'Log in to unlock your account.',
  'Kindly log in to proceed with your session.',
  'Hi there! Please log in to start your journey.',
  'Log in to explore our tools and features.',
  'Please log in to access your portfolio.',
  'To continue, log in to your account.',
  'Welcome back! Log in to proceed.',
  "Let's get started—please log in first.",
  'Please authenticate by logging in.',
  'Log in to access tailored insights.',
  'We need you to log in to assist further.',
  'Please log in to continue exploring.',
  'Welcome! Your first step is to log in.',
  'Log in to dive into the financial details.',
  'Access the system by logging in now.',
  'To proceed, log in securely.',
  'Please log in to access blockchain tools.',
  'Your personalized support starts with logging in.',
  'Hi! Please log in to manage your portfolio.',
  "To begin, ensure you're logged in.",
  'Log in to access crypto insights.',
  'Welcome! Please authenticate by logging in.',
  'Kindly log in to get started with Web3 tools.',
  'Log in to access investment strategies.',
  'We need you to log in to provide support.',
  'Please log in to view your holdings.',
  'Log in to discover liquidity opportunities.',
  'Your first step: log in to the platform.',
  'Welcome back! Please log in for updates.',
  'Log in to explore swap functionalities.',
  'To proceed, log in to your account.',
  'Secure your session by logging in now.',
  'Hi! Please log in for portfolio analysis.',
  'Log in to receive financial insights.',
  'Before we continue, kindly log in.',
  'Authenticate to proceed by logging in.',
  'To start, log in and access the tools.',
  'Welcome! Please log in to move forward.',
  'Log in to unlock your crypto data.',
  'Secure access starts with logging in.',
  'Log in to leverage our blockchain tools.',
  'Before we proceed, please log in.',
  'Log in to continue your financial journey.',
  'Hi there! Kindly log in to proceed.',
  'Welcome back! Log in to view updates.',
  'Log in to unlock personalized support.',
  'Please log in to start using our platform.',
  'To continue, log in to your secure account.',
  'Log in to access advanced features.',
  'Authenticate by logging in to proceed.',
  'Welcome! Log in to explore further.',
  "Hi! Please ensure you're logged in to start.",
  'Your next step: log in to proceed.',
  'To begin, log in to access your tools.',
  'Log in to view detailed portfolio insights.',
  'Log in now to secure your session.',
  'Access premium tools by logging in.',
  'Welcome back! Please log in to continue.',
  'Log in to receive portfolio recommendations.',
  'Please log in for blockchain analytics.',
  'To proceed, please log in first.',
  'Log in to access market insights.',
  'Your first step: log in securely.',
  'Please log in to optimize your session.',
  'Log in to access advanced analytics.',
  'Authenticate by logging in to continue.',
  'Welcome! Log in to see your account.',
  'Hi there! Log in to explore investment options.',
  'Please log in to proceed with tailored guidance.',
  'Log in to begin managing your assets.',
  'Secure your portfolio by logging in.',
  'To start, log in and access portfolio tools.',
  'Please log in to enhance your experience.',
  'Log in to unlock detailed market data.',
  "To proceed, ensure you're logged in.",
  'Welcome! Log in to personalize your session.',
  'Please log in to proceed to the account.',
  'Authenticate now by logging in.',
  'Log in to receive accurate financial insights.',
  'Access crypto trends by logging in.',
  'Welcome back! Log in for real-time updates.',
  'Please log in to explore investment strategies.',
  'Your first step: log in to the system.',
  'Secure access starts by logging in.',
  'Hi! Please log in to access all features.',
];
