export const mathAdapter = (string: string) =>
  string
    .replace(/\\\\n/g, '\n')
    .replace(/\\n/g, '\n')
    .replace(/\n-\*\*/g, '\n- **')
    .replace(/\\*\$/g, '\uFF04')
    .replace(/\\\\\[/g, '\n$$')
    .replace(/\\\\\]/g, '$$ ')
    .replace(/\\\\\(/g, '\n$$')
    .replace(/\\\\\)/g, '$$')
    .replace(/\\\\text/g, '\\text')
    .replace(/\\\\frac/g, '\\frac')
    .replace(/\\\\approx/g, '\\approx')
    .replace(/\\\\times/g, '\\times')
    .replace(/\\\\left/g, '\\left')
    .replace(/\\\\right/g, '\\right')
    .replace(/\\\\sum/g, '\\sum')
    .replace(/\\\\int/g, '\\int')
    .replace(/\\\\lim/g, '\\lim')
    .replace(/\\\\sin/g, '\\sin')
    .replace(/\\\\cos/g, '\\cos')
    .replace(/\\\\tan/g, '\\tan')
    .replace(/\\\\log/g, '\\log')
    .replace(/\\\\ln/g, '\\ln')
    .replace(/\\\\sqrt/g, '\\sqrt')
    .replace(/\\\\cdot/g, '\\cdot')
    .replace(/\\\\pi/g, '\\pi')
    .replace(/\\\\alpha/g, '\\alpha')
    .replace(/\\\\beta/g, '\\beta')
    .replace(/\\\\gamma/g, '\\gamma')
    .replace(/\\\\delta/g, '\\delta')
    .replace(/\\\\epsilon/g, '\\epsilon')
    .replace(/\\\\mu/g, '\\mu')
    .replace(/\\\\sigma/g, '\\sigma')
    .replace(/\\\\begin\{equation\}/g, '\\begin{equation}')
    .replace(/\\\\end\{equation\}/g, '\\end{equation}')
    .replace(/\\\\begin\{align\}/g, '\\begin{align}')
    .replace(/\\\\end\{align\}/g, '\\end{align}')
    .replace(/\\\\begin\{align\*}/g, '\\begin{align*}')
    .replace(/\\\\end\{align\*}/g, '\\end{align*}')
    .replace(/\\\\frac/g, '\\frac')
    .replace(/\\\\left\{/g, '\\left{')
    .replace(/\\\\right\}/g, '\\right}')
    .replace(/\\\\left\[/g, '\\left[')
    .replace(/\\\\right\]/g, '\\right]')
    .replace(/\\\\left\(/g, '\\left(')
    .replace(/\\\\right\)/g, '\\right)')
    .replace(/\\\\texttt/g, '\\texttt')
    .replace(/\\\\mathbf/g, '\\mathbf')
    .replace(/\\\\mathcal/g, '\\mathcal')
    .replace(/\\\\mathbb/g, '\\mathbb')
    .replace(/\\\\mathfrak/g, '\\mathfrak')
    .replace(/\\\\:/g, '\\:')
    .replace(/\\\\_/g, ' ')
    .replace(/\\\\;/g, '\\;')
    .replace(/\\\\,/g, '\\,')
    .replace(/\\\\quad/g, '\\quad')
    .replace(/\\\\qquad/g, '\\qquad')
    .replace(/Total_/g, 'Total ')
    .replace(/Withdraw_/g, 'Withdraw ')
    .replace(/Deposit_/g, 'Deposit ')
    .replace(/\n/g, '  \n');
